version: "2"
services:
  app:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/hucpa
  postgres:
    environment:
      POSTGRES_USER: hucpa
      POSTGRES_PASSWORD: hucpa
    image: postgres:9.6.1
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
